### ISSUE TITLE
Create PIPE does not use proper DATABASE 

### ISSUE THREAD

**Issue by marcinef** [chanzuckerberg/terraform-provider-snowflake#135] opened 2020-01-30 20:58 UTC
I tested new feature in 0.10.0 
-  create snowflake_pipe 

but it fails to use specified database.

The plan looks good:

```
  # snowflake_pipe.pipe will be created
  + resource "snowflake_pipe" "pipe" {
      + auto_ingest          = false
      + comment              = "Snowpipe for my amazing data"
      + copy_statement       = "COPY INTO SOME DATABASE.SCHEMA "
      + database             = "MY-DB"
      + id                   = (known after apply)
      + name                 = "snow-pipe-data"
      + notification_channel = (known after apply)
      + owner                = (known after apply)
      + schema               = "PUBLIC"
    }
```

However the apply fails to use specified DATABASE:

```
Error: error creating pipe snow-pipe-data: 090105 (22000): Cannot perform operation. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.

  on pipe.tf line 1, in resource "snowflake_pipe" "pipe":
   1: resource "snowflake_pipe" "pipe" {
```

**Comment by sjauld** [comment] 2020-02-20 03:23
It's likely that this is due to the hyphen in your database name. Hyphens are not currently escaped.

**Comment by ryanking** [comment] 2020-02-27 17:46
@sjauld good catch. we are planning some work to overhaul the way we generate queries. I will make sure to add this to the list of things to fix

**Comment by msluyter** [comment] 2020-06-12 14:01
Does the issue also occur with underscores? Getting same error; no hyphens, but with a name like 'FOO_BAR'.

**Comment by NiallRees** [comment] 2020-07-02 12:50
Also running to this issue with a database name including an underscore.

**Comment by NiallRees** [comment] 2020-07-02 13:14
> @sjauld good catch. we are planning some work to overhaul the way we generate queries. I will make sure to add this to the list of things to fix

If you're able to point me to the section of code which generates the 'use db' query I can submit a PR

**Comment by harrydaniels-IW** [comment] 2020-07-29 16:36
I have the same underscore issue, is there a workaround?

**Comment by NiallRees** [comment] 2020-07-29 16:37
> I have the same underscore issue, is there a workaround?

So far I've been creating the pipes manually and then importing them into the terraform state so that at least there's a record they exist. You can't modify them through terraform though without the same issue as above

**Comment by ryanking** [comment] 2020-07-29 22:03
> If you're able to point me to the section of code which generates the 'use db' query I can submit a PR

The identifiers are quoted, so I don't think this is the problem. Either way the code for generating the queries is [here](https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/master/pkg/snowflake/pipe.go) or can be found by starting there.

I would like to help fix this, but given that my team doesn't use this resource my context on how it works is somewhat limited.

What would *really* help is if someone could write an acceptance test for this resource. One that reproduces this bug would be 💯 .

**Comment by NiallRees** [comment] 2020-07-31 10:53
> > If you're able to point me to the section of code which generates the 'use db' query I can submit a PR
> 
> The identifiers are quoted, so I don't think this is the problem. Either way the code for generating the queries is [here](https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/master/pkg/snowflake/pipe.go) or can be found by starting there.
> 
> I would like to help fix this, but given that my team doesn't use this resource my context on how it works is somewhat limited.
> 
> What would _really_ help is if someone could write an acceptance test for this resource. One that reproduces this bug would be 💯 .

Very happy to, please could the development guide be improved in the readme first? 

```
To do development you need Go installed, this repo cloned and that's about it.
```

isn't true unfortunately! I'm having real issues getting the local tests working. I first had to install goimports globally, and now can't run the tests successfully

```➜  terraform-provider-snowflake git:(master) ✗ make test
goimports -w -d $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./dist/*")
./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/what@v1.0.0/main.go:1:16: expected ';', found '.'
./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/tempmod/main.go:1:16: expected ';', found '.'
./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/extra/geez/help.go:1:16: expected ';', found '.'
./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/extra/yo.go:1:16: expected ';', found '.'
./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/extra/v2/geez/help.go:1:16: expected ';', found '.'
./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/extra/v2/me.go:1:16: expected ';', found '.'
./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/what@v1.1.0/main.go:1:16: expected ';', found '.'```

**Comment by NiallRees** [comment] 2020-07-31 13:21
> > > If you're able to point me to the section of code which generates the 'use db' query I can submit a PR
> > 
> > 
> > The identifiers are quoted, so I don't think this is the problem. Either way the code for generating the queries is [here](https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/master/pkg/snowflake/pipe.go) or can be found by starting there.
> > I would like to help fix this, but given that my team doesn't use this resource my context on how it works is somewhat limited.
> > What would _really_ help is if someone could write an acceptance test for this resource. One that reproduces this bug would be 💯 .
> 
> Very happy to, please could the development guide be improved in the readme first?
> 
> ```
> To do development you need Go installed, this repo cloned and that's about it.
> ```
> 
> isn't true unfortunately! I'm having real issues getting the local tests working. I first had to install goimports globally, and now can't run the tests successfully
> 
> ```
> goimports -w -d $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./dist/*")
> ./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/what@v1.0.0/main.go:1:16: expected ';', found '.'
> ./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/tempmod/main.go:1:16: expected ';', found '.'
> ./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/extra/geez/help.go:1:16: expected ';', found '.'
> ./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/extra/yo.go:1:16: expected ';', found '.'
> ./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/extra/v2/geez/help.go:1:16: expected ';', found '.'
> ./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/extra/v2/me.go:1:16: expected ';', found '.'
> ./src/golang.org/x/tools/go/packages/packagestest/testdata/groups/two/modules/example.com/what@v1.1.0/main.go:1:16: expected ';', found '.'```
> ```

Ok working I'll write up some better set up in the docs too

**Comment by NiallRees** [comment] 2020-07-31 15:23
The issue for me was that the copy statement did not include the database name. This led to the error of 

```
error creating pipe DBT_RUN_RESULTS_TEST: 090105 (22000): Cannot perform operation. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
```

I overcame the problem by fully specifying all references with DB_NAME.SCHEMA_NAME.STAGE/TABLE

As the provider does execute a `USE DATABASE` command, you must fully specify all names.

Solved I think @ryanking

**Comment by ryanking** [comment] 2020-12-08 04:55
Going to close this for now, if someone wants to write up or code a feature to make this better, go for it.

**Closed by ryanking** 2020-12-08 04:55 UTC
Labels: bug

**Comment by asad3gh** [comment] 2024-05-01 17:41
I still have issues creating snowpipe using Terraform
Snowflake provider version is 0.89
If I specified a fully qualified name with db.schema.table --> Getting this error "This session does not have a current database"

If I specify just the table name --> i get table not found

Please advise

**Comment by sfc-gh-jcieslak** [comment] 2024-05-07 06:25
@asad3gh please create a new GitHub issue using general usage template if you're still having this issue.
