### ISSUE TITLE
Resource snowflake_integration_grant does not correctly set terraform state for privilege USAGE

### ISSUE THREAD

**Issue by teej** [chanzuckerberg/terraform-provider-snowflake#167] opened 2020-04-10 00:04 UTC
When using the `USAGE` role with a `snowflake_integration_grant`, Terraform state is not correctly updated. The result is that every run of `terraform apply` will perform this grant because it believes that terraform state and the resource state don't match.

If I create a terraform project with a single resource as:
```
resource "snowflake_integration_grant" "my_integration_grant" {
  integration_name = "MY_STORAGE_INTEGRATION"
  privilege        = "USAGE"
  roles            = ["MY_ROLE"]
}
```

If I then apply that and inspect terraform state, I can see that the role is not reflected.
```bash
% tf state show snowflake_integration_grant.my_integration_grant                  
# snowflake_integration_grant.my_integration_grant:
resource "snowflake_integration_grant" "my_integration_grant" {
    id               = "MY_STORAGE_INTEGRATION|||USAGE"
    integration_name = "MY_STORAGE_INTEGRATION"
    privilege        = "USAGE"
    roles            = []
}
```

The resource `snowflake_integration_grant` has it's roles set using `readGenericGrant` in `pkg/resources/grant_helpers.go`. As stated in that function, `"We re-aggregate grants that would be equivalent to the "ALL" grant"`. The problem is that for a Snowflake storage integration, `USAGE` is the only type of grant. So any `USAGE` grant in this code is rolled up into `ALL`, which is then later filtered out in the call to `ALLPrivsPresent`.

As a workaround I can specify the `ALL` grant instead of `USAGE`. This is not desirable as my intent is to just grant `USAGE`, not all future privileges that Snowflake might add.

**Comment by ryanking** [comment] 2020-07-29 22:08
@teej I haven't had a chance to dig into this, but I have observed that snowflake will do some annoying things when you grant a privilege which is already covered by a broader grant. Is it possible that USAGE is already granted in another way?

**Comment by foresterr** [comment] 2020-08-07 11:01
I have also observed almost the same behavior, and I can confirm it's not caused by overlapping grants in Snowflake - at the moment I was checking, there was only a single USAGE grant on the integration (the one added via Terraform).

I'm saying "almost" because in my case the roles get stored in state just fine, but Terraform still insists to recreate the grant resource every time.

Workaround with "ALL" is working for me too, so it indeed looks like there is a problem with handling ALL when there is only one possible privilege. It's tricky, though, because as far as I know there is no way to tell from looking at grants in Snowflake whether one was granted explicitly or via ALL. So in case of resource grants in Terraform with only one type of grant possible, either ALL would work, or the explicit grant would work, but never both, at least not as it's currently implemented.

Note, if this is indeed the cause, then it should be possible to recreate the issue on **_any_** grant resource by explicitly granting every possible privilege to the same object by separate grant resources. Then provider will start thinking actual privileges on object were granted by ALL, and behave in the same way as with this issue.

**Comment by ryanking** [comment] 2020-12-08 04:53
Going to close this as we are going to be [removing support for ALL grants](https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/318).

If still occurring after that, feel free to re-open.

**Closed by ryanking** 2020-12-08 04:53 UTC
Labels: bug
